data_path:
    pos: "dataset/interactions.csv"
    neg: "dataset/unobserved_interactions.csv"
data_test_path: "dataset/test_interactions.csv"
random_sample_test_KNN: 100
NCF_model_path : "modelsNCF/test"